version: 2

common_cache_key: &common_cache_key
  key: dependency-cache-{{ checksum "../ocaml-version" }}-{{ checksum ".circleci/config.yml" }}-{{ checksum "lambda-runtime.opam" }}

esy_cache_key: &esy_cache_key
  key: esy-cache-{{ checksum "esy.json" }}-{{ checksum "../esy-checksum" }}-{{ checksum ".circleci/config.yml" }}

esy_post_build_cache_key: &esy_post_build_cache_key
  key: esy-post-build-cache-{{ checksum "esy.json" }}-{{ checksum "../esy-checksum" }}-{{ checksum ".circleci/config.yml" }}

opam-steps: &opam-steps
  steps:
    - checkout
    - run:
        name: "Note OCAML_VERSION for cache"
        command: echo $OCAML_VERSION > ../ocaml-version
    - restore_cache:
        <<: *common_cache_key
    - run:
        name: "Initialize opam"
        command: |
          sudo apt-get install -y m4
          opam init --auto-setup --dot-profile=~/.bash_profile
          opam remote add ocamlorg https://opam.ocaml.org || true
          opam remote remove default || true
    - run:
        name: "Install deps"
        command: |
          sudo apt-get install -y pkg-config libncurses5-dev
          opam update
          opam install -y dune
          opam install -y ocamlformat
    - run:
        name: 'Clean'
        command: rm -rf ./_build
    - run:
        name: 'opam pin'
        command: |
          opam install reason
          opam install alcotest
          opam install -t --deps-only .
    - save_cache:
        <<: *common_cache_key
        paths:
          - ~/.opam
    - run:
        name: 'Test'
        command: |
          source ~/.bash_profile
          eval `opam config env`
          opam pin add -t -y lambda-runtime .
          opam pin add -t -y now .
          dune build @all
          dune runtest --no-buffer
    - run:
        name: 'Check code is formatted with ocamlformat'
        command: |
          eval `opam config env`
          case $OCAML_VERSION in
          4.04.*|4.05.*)
            echo "unsupported OCaml version for ocamlformat"
          ;;
          *)
            dune build @fmt --auto-promote
            git diff --exit-code
          esac
    - run:
        name: 'Check git is clean'
        command: git diff --exit-code

jobs:
  4.04.2:
    docker:
      - image: ocaml/opam2:debian-9-ocaml-4.04
    environment:
      - TERM: dumb
      - OCAML_VERSION: "4.04.2"
    <<: *opam-steps
  4.05.0:
    docker:
      - image: ocaml/opam2:debian-9-ocaml-4.05
    environment:
      - TERM: dumb
      - OCAML_VERSION: "4.05.0"
    <<: *opam-steps
  4.06.1:
    docker:
      - image: ocaml/opam2:debian-9-ocaml-4.06
    environment:
      - TERM: dumb
      - OCAML_VERSION: "4.06.1"
    <<: *opam-steps
  4.07.1:
    docker:
      - image: ocaml/opam2:debian-9-ocaml-4.07
    environment:
      - TERM: dumb
      - OCAML_VERSION: "4.07.1"
    <<: *opam-steps
  4.08.1:
    docker:
      - image: ocaml/opam2:debian-9-ocaml-4.08
    environment:
      - TERM: dumb
      - OCAML_VERSION: "4.08.1"
    <<: *opam-steps
  esy:
    docker:
      - image: circleci/node:7.10
      # - image: ocaml/opam2:debian-9-ocaml-4.06
    environment:
      - TERM: dumb
      - NPM_CONFIG_PREFIX: "~/.npm-global"
    steps:
      - checkout
      - run:
          name: 'Note esy.lock checksum for cache'
          command: find esy.lock -type f -exec md5sum {} \; | sort -k 2 | md5sum > ../esy-checksum
      - restore_cache:
          <<: *esy_cache_key
      - restore_cache:
          <<: *esy_post_build_cache_key
      - run:
          name: "Install esy"
          command: npm install -g esy@0.5.6
      # - run:
      #     name: 'Clean'
      #     command: make clean-for-ci
      - run:
          name: 'esy install'
          command: ~/.npm-global/bin/esy install
      - save_cache:
          <<: *esy_cache_key
          paths:
            - ~/.npm-global
            - ~/.esy
            - node_modules
            - _esy
      - run:
          name: 'esy build'
          # Reason is a dev dependency
          command: ~/.npm-global/bin/esy dune build @all
      - run:
          name: 'esy test'
          command: ~/.npm-global/bin/esy b dune runtest --no-buffer
      - run:
          name: 'Check code is formatted with ocamlformat'
          command: |
            ~/.npm-global/bin/esy dune build @fmt --auto-promote
            git diff --exit-code
      # Use both pre and post build caches so that we're more likely
      # to have dependencies cached. `esy build` is more likely to fail,
      # so this will make the push that fixes the build faster
      - save_cache:
          <<: *esy_post_build_cache_key
          paths:
            - ~/.esy
            - node_modules
            - _esy

workflows:
  version: 2
  build-deploy:
    jobs:
      - 4.04.2
      - 4.05.0
      - 4.06.1
      - 4.07.1
      - 4.08.1
      - esy
